import StringIO,csv

'''
Data from

https://data.gov.uk/dataset/england-nhs-connecting-for-health-organisation-data-service-data-files-of-nhsorganisations

'''

buf=StringIO.StringIO('''00C,NHS DARLINGTON CCG,COUNTY DURHAM,DL3 6JL
00D,"NHS DURHAM DALES, EASINGTON AND SEDGEFIELD CCG",CLEVELAND,TS21 3EE
00F,NHS GATESHEAD CCG,TYNE AND WEAR,NE15 8NY
00G,NHS NEWCASTLE NORTH AND EAST CCG,TYNE AND WEAR,NE15 8NY
00H,NHS NEWCASTLE WEST CCG,TYNE AND WEAR,NE15 8NY
00J,NHS NORTH DURHAM CCG,COUNTY DURHAM,DH1 5TS
00K,NHS HARTLEPOOL AND STOCKTON-ON-TEES CCG,CLEVELAND,TS23 2LA
00L,NHS NORTHUMBERLAND CCG,NORTHUMBERLAND,NE61 2EF
00M,NHS SOUTH TEES CCG,CLEVELAND,TS3 6AL
00N,NHS SOUTH TYNESIDE CCG,TYNE AND WEAR,NE32 5NN
00P,NHS SUNDERLAND CCG,TYNE AND WEAR,SR5 3XB
00Q,NHS BLACKBURN WITH DARWEN CCG,LANCASHIRE,BB1 2FD
00R,NHS BLACKPOOL CCG,LANCASHIRE,FY1 6JX
00T,NHS BOLTON CCG,LANCASHIRE,BL1 1PP
00V,NHS BURY CCG,LANCASHIRE,BL9 0EN
00W,NHS CENTRAL MANCHESTER CCG,GREATER MANCHESTER,M14 7LU
00X,NHS CHORLEY AND SOUTH RIBBLE CCG,LANCASHIRE,PR26 6TR
00Y,NHS OLDHAM CCG,LANCASHIRE,OL9 6EE
01A,NHS EAST LANCASHIRE CCG,LANCASHIRE,BB9 8AS
01C,NHS EASTERN CHESHIRE CCG,CHESHIRE,SK10 3BL
01D,"NHS HEYWOOD, MIDDLETON AND ROCHDALE CCG",LANCASHIRE,OL16 1XU
01E,NHS GREATER PRESTON CCG,LANCASHIRE,PR26 6TR
01F,NHS HALTON CCG,CHESHIRE,WA7 5TD
01G,NHS SALFORD CCG,LANCASHIRE,M6 5FW
01H,NHS CUMBRIA CCG,CUMBRIA,CA10 2HX
01J,NHS KNOWSLEY CCG,MERSEYSIDE,L36 6GA
01K,NHS LANCASHIRE NORTH CCG,LANCASHIRE,LA1 1QD
01M,NHS NORTH MANCHESTER CCG,GREATER MANCHESTER,M40 1HA
01N,NHS SOUTH MANCHESTER CCG,GREATER MANCHESTER,M14 7LU
01R,NHS SOUTH CHESHIRE CCG,CHESHIRE,CW5 5QU
01T,NHS SOUTH SEFTON CCG,MERSEYSIDE,L20 3DL
01V,NHS SOUTHPORT AND FORMBY CCG,LANCASHIRE,PR8 6PL
01W,NHS STOCKPORT CCG,CHESHIRE,SK4 1BS
01X,NHS ST HELENS CCG,MERSEYSIDE,WA10 1FY
01Y,NHS TAMESIDE AND GLOSSOP CCG,GREATER MANCHESTER,M34 2GP
02A,NHS TRAFFORD CCG,CHESHIRE,M33 7FT
02D,NHS VALE ROYAL CCG,CHESHIRE,CW5 5QU
02E,NHS WARRINGTON CCG,CHESHIRE,WA3 7QN
02F,NHS WEST CHESHIRE CCG,CHESHIRE,CH2 1HJ
02G,NHS WEST LANCASHIRE CCG,LANCASHIRE,L39 2AS
02H,NHS WIGAN BOROUGH CCG,LANCASHIRE,WN1 1NJ
02M,NHS FYLDE & WYRE CCG,LANCASHIRE,PR4 3AL
02N,"NHS AIREDALE, WHARFEDALE AND CRAVEN CCG",WEST YORKSHIRE,BD5 7JR
02P,NHS BARNSLEY CCG,SOUTH YORKSHIRE,S75 2PY
02Q,NHS BASSETLAW CCG,NOTTINGHAMSHIRE,DN22 7XF
02R,NHS BRADFORD DISTRICTS CCG,WEST YORKSHIRE,BD5 7JR
02T,NHS CALDERDALE CCG,WEST YORKSHIRE,HX3 5AX
02V,NHS LEEDS NORTH CCG,WEST YORKSHIRE,LS17 5BP
02W,NHS BRADFORD CITY CCG,WEST YORKSHIRE,BD5 7JR
02X,NHS DONCASTER CCG,SOUTH YORKSHIRE,DN4 5DJ
02Y,NHS EAST RIDING OF YORKSHIRE CCG,NORTH HUMBERSIDE,HU10 6DT
03A,NHS GREATER HUDDERSFIELD CCG,WEST YORKSHIRE,HD2 1GZ
03C,NHS LEEDS WEST CCG,WEST YORKSHIRE,LS16 6EB
03D,"NHS HAMBLETON, RICHMONDSHIRE AND WHITBY CCG",NORTH YORKSHIRE,DL6 2UU
03E,NHS HARROGATE AND RURAL DISTRICT CCG,NORTH YORKSHIRE,HG5 8QB
03F,NHS HULL CCG,NORTH HUMBERSIDE,HU1 1UY
03G,NHS LEEDS SOUTH AND EAST CCG,WEST YORKSHIRE,LS15 8ZB
03H,NHS NORTH EAST LINCOLNSHIRE CCG,SOUTH HUMBERSIDE,DN31 2UJ
03J,NHS NORTH KIRKLEES CCG,WEST YORKSHIRE,WF12 8DJ
03K,NHS NORTH LINCOLNSHIRE CCG,SOUTH HUMBERSIDE,DN20 8GS
03L,NHS ROTHERHAM CCG,SOUTH YORKSHIRE,S66 1YY
03M,NHS SCARBOROUGH AND RYEDALE CCG,NORTH YORKSHIRE,YO11 2HG
03N,NHS SHEFFIELD CCG,SOUTH YORKSHIRE,S9 4EU
03Q,NHS VALE OF YORK CCG,NORTH YORKSHIRE,YO30 4GQ
03R,NHS WAKEFIELD CCG,WEST YORKSHIRE,WF1 1LT
03T,NHS LINCOLNSHIRE EAST CCG,LINCOLNSHIRE,LN4 2HN
03V,NHS CORBY CCG,NORTHAMPTONSHIRE,NN17 2UR
03W,NHS EAST LEICESTERSHIRE AND RUTLAND CCG,LEICESTERSHIRE,LE4 8BL
03X,NHS EREWASH CCG,DERBYSHIRE,DE7 5FH
03Y,NHS HARDWICK CCG,DERBYSHIRE,S41 7PF
04C,NHS LEICESTER CITY CCG,LEICESTERSHIRE,LE1 6NB
04D,NHS LINCOLNSHIRE WEST CCG,LINCOLNSHIRE,LN4 2HN
04E,NHS MANSFIELD AND ASHFIELD CCG,NOTTINGHAMSHIRE,NG21 0HJ
04F,NHS MILTON KEYNES CCG,BUCKINGHAMSHIRE,MK3 6RT
04G,NHS NENE CCG,NORTHAMPTONSHIRE,NN3 6BF
04H,NHS NEWARK & SHERWOOD CCG,NOTTINGHAMSHIRE,NG24 3HJ
04J,NHS NORTH DERBYSHIRE CCG,DERBYSHIRE,S41 7PF
04K,NHS NOTTINGHAM CITY CCG,NOTTINGHAMSHIRE,NG1 6GN
04L,NHS NOTTINGHAM NORTH AND EAST CCG,NOTTINGHAMSHIRE,NG5 0TE
04M,NHS NOTTINGHAM WEST CCG,NOTTINGHAMSHIRE,NG9 8DB
04N,NHS RUSHCLIFFE CCG,NOTTINGHAMSHIRE,NG11 6LQ
04Q,NHS SOUTH WEST LINCOLNSHIRE CCG,LINCOLNSHIRE,LN4 2HN
04R,NHS SOUTHERN DERBYSHIRE CCG,DERBYSHIRE,DE1 3QT
04V,NHS WEST LEICESTERSHIRE CCG,LEICESTERSHIRE,LE11 2TZ
04X,NHS BIRMINGHAM SOUTH AND CENTRAL CCG,WEST MIDLANDS,B16 9PA
04Y,NHS CANNOCK CHASE CCG,STAFFORDSHIRE,WS11 1JP
05A,NHS COVENTRY AND RUGBY CCG,WEST MIDLANDS,CV1 2GQ
05C,NHS DUDLEY CCG,WEST MIDLANDS,DY5 1RU
05D,NHS EAST STAFFORDSHIRE CCG,STAFFORDSHIRE,DE14 2WF
05F,NHS HEREFORDSHIRE CCG,HEREFORDSHIRE,HR1 1SH
05G,NHS NORTH STAFFORDSHIRE CCG,STAFFORDSHIRE,ST5 1QG
05H,NHS WARWICKSHIRE NORTH CCG,WARWICKSHIRE,CV34 4DE
05J,NHS REDDITCH AND BROMSGROVE CCG,WORCESTERSHIRE,B61 0TX
05L,NHS SANDWELL AND WEST BIRMINGHAM CCG,WEST MIDLANDS,B70 9LD
05N,NHS SHROPSHIRE CCG,SHROPSHIRE,SY3 8XL
05P,NHS SOLIHULL CCG,WEST MIDLANDS,B90 4BN
05Q,NHS SOUTH EAST STAFFORDSHIRE AND SEISDON PENINSULA CCG,STAFFORDSHIRE,B78 3HF
05R,NHS SOUTH WARWICKSHIRE CCG,WARWICKSHIRE,CV34 4DE
05T,NHS SOUTH WORCESTERSHIRE CCG,WORCESTERSHIRE,WR5 2LG
05V,NHS STAFFORD AND SURROUNDS CCG,STAFFORDSHIRE,ST16 2ST
05W,NHS STOKE ON TRENT CCG,STAFFORDSHIRE,ST4 7PZ
05X,NHS TELFORD AND WREKIN CCG,SHROPSHIRE,TF7 4BF
05Y,NHS WALSALL CCG,WEST MIDLANDS,WS2 7JL
06A,NHS WOLVERHAMPTON CCG,WEST MIDLANDS,WV10 9RU
06D,NHS WYRE FOREST CCG,WORCESTERSHIRE,B61 0TX
06F,NHS BEDFORDSHIRE CCG,BEDFORDSHIRE,MK45 4HR
06H,NHS CAMBRIDGESHIRE AND PETERBOROUGH CCG,CAMBRIDGESHIRE,CB2 8FH
06K,NHS EAST AND NORTH HERTFORDSHIRE CCG,HERTFORDSHIRE,AL8 6JL
06L,NHS IPSWICH AND EAST SUFFOLK CCG,SUFFOLK,IP8 4DE
06M,NHS GREAT YARMOUTH AND WAVENEY CCG,SUFFOLK,NR34 9BN
06N,NHS HERTS VALLEYS CCG,HERTFORDSHIRE,HP2 7YU
06P,NHS LUTON CCG,BEDFORDSHIRE,LU1 2BJ
06Q,NHS MID ESSEX CCG,ESSEX,CM2 5PF
06T,NHS NORTH EAST ESSEX CCG,ESSEX,CO4 5JR
06V,NHS NORTH NORFOLK CCG,NORFOLK,NR11 6LZ
06W,NHS NORWICH CCG,NORFOLK,NR2 1NH
06Y,NHS SOUTH NORFOLK CCG,NORFOLK,NR7 0WG
07G,NHS THURROCK CCG,ESSEX,SS14 3HG
07H,NHS WEST ESSEX CCG,ESSEX,CM16 6TN
07J,NHS WEST NORFOLK CCG,NORFOLK,PE30 1EX
07K,NHS WEST SUFFOLK CCG,SUFFOLK,IP33 3PH
07L,NHS BARKING AND DAGENHAM CCG,ESSEX,IG11 9LX
07M,NHS BARNET CCG,MIDDLESEX,HA8 0AD
07N,NHS BEXLEY CCG,KENT,DA7 6HZ
07P,NHS BRENT CCG,MIDDLESEX,HA0 4UZ
07Q,NHS BROMLEY CCG,KENT,BR3 3QL
07R,NHS CAMDEN CCG,GREATER LONDON,NW1 2PL
07T,NHS CITY AND HACKNEY CCG,GREATER LONDON,N1 5HZ
07V,NHS CROYDON CCG,SURREY,CR0 9XT
07W,NHS EALING CCG,GREATER LONDON,W5 2HL
07X,NHS ENFIELD CCG,HERTFORDSHIRE,EN4 0DY
07Y,NHS HOUNSLOW CCG,MIDDLESEX,TW3 3HR
08A,NHS GREENWICH CCG,GREATER LONDON,SE10 9LR
08C,NHS HAMMERSMITH AND FULHAM CCG,GREATER LONDON,NW1 5JD
08D,NHS HARINGEY CCG,GREATER LONDON,N22 8HQ
08E,NHS HARROW CCG,MIDDLESEX,HA1 3AW
08F,NHS HAVERING CCG,ESSEX,RM1 3PJ
08G,NHS HILLINGDON CCG,MIDDLESEX,UB8 1QG
08H,NHS ISLINGTON CCG,GREATER LONDON,EC1V 7LQ
08J,NHS KINGSTON CCG,SURREY,KT1 1EU
08K,NHS LAMBETH CCG,GREATER LONDON,SE1 7NT
08L,NHS LEWISHAM CCG,GREATER LONDON,SE12 8RN
08M,NHS NEWHAM CCG,GREATER LONDON,E16 1DR
08N,NHS REDBRIDGE CCG,ESSEX,IG1 2QX
08P,NHS RICHMOND CCG,MIDDLESEX,TW1 3BZ
08Q,NHS SOUTHWARK CCG,GREATER LONDON,SE1 2QH
08R,NHS MERTON CCG,GREATER LONDON,SW19 1RH
08T,NHS SUTTON CCG,SURREY,SM3 8LR
08V,NHS TOWER HAMLETS CCG,GREATER LONDON,E1 4DG
08W,NHS WALTHAM FOREST CCG,GREATER LONDON,E11 1HP
08X,NHS WANDSWORTH CCG,GREATER LONDON,SW15 2SR
08Y,NHS WEST LONDON CCG,GREATER LONDON,NW1 5JD
09A,NHS CENTRAL LONDON (WESTMINSTER) CCG,GREATER LONDON,NW1 5JD
09C,NHS ASHFORD CCG,KENT,TN25 4AB
09D,NHS BRIGHTON AND HOVE CCG,EAST SUSSEX,BN1 4FU
09E,NHS CANTERBURY AND COASTAL CCG,KENT,CT1 1YW
09F,"NHS EASTBOURNE, HAILSHAM AND SEAFORD CCG",EAST SUSSEX,BN7 2PB
09G,NHS COASTAL WEST SUSSEX CCG,WEST SUSSEX,BN12 6BT
09H,NHS CRAWLEY CCG,WEST SUSSEX,RH11 7DH
09J,"NHS DARTFORD, GRAVESHAM AND SWANLEY CCG",KENT,DA12 1AU
09L,NHS EAST SURREY CCG,SURREY,KT22 9AE
09N,NHS GUILDFORD AND WAVERLEY CCG,SURREY,GU1 3EL
09P,NHS HASTINGS AND ROTHER CCG,EAST SUSSEX,TN40 2DZ
09W,NHS MEDWAY CCG,KENT,ME4 4EL
09X,NHS HORSHAM AND MID SUSSEX CCG,WEST SUSSEX,RH11 7DH
09Y,NHS NORTH WEST SURREY CCG,SURREY,KT13 8DY
10A,NHS SOUTH KENT COAST CCG,KENT,CT16 3PJ
10C,NHS SURREY HEATH CCG,SURREY,GU15 3HD
10D,NHS SWALE CCG,KENT,ME10 2ST
10E,NHS THANET CCG,KENT,CT9 1XZ
10G,NHS BRACKNELL AND ASCOT CCG,BERKSHIRE,SL4 3DP
10H,NHS CHILTERN CCG,BUCKINGHAMSHIRE,HP7 0JD
10J,NHS NORTH HAMPSHIRE CCG,HAMPSHIRE,RG24 7AE
10K,NHS FAREHAM AND GOSPORT CCG,HAMPSHIRE,PO17 6AR
10L,NHS ISLE OF WIGHT CCG,ISLE OF WIGHT,PO30 5TG
10M,NHS NEWBURY AND DISTRICT CCG,BERKSHIRE,RG18 3AS
10N,NHS NORTH & WEST READING CCG,BERKSHIRE,RG30 2BA
10Q,NHS OXFORDSHIRE CCG,OXFORDSHIRE,OX4 2LH
10R,NHS PORTSMOUTH CCG,HAMPSHIRE,PO4 8LD
10T,NHS SLOUGH CCG,BERKSHIRE,SL1 2BJ
10V,NHS SOUTH EASTERN HAMPSHIRE CCG,HAMPSHIRE,PO17 6AR
10W,NHS SOUTH READING CCG,BERKSHIRE,RG2 7HE
10X,NHS SOUTHAMPTON CCG,HAMPSHIRE,SO16 4GX
10Y,NHS AYLESBURY VALE CCG,BUCKINGHAMSHIRE,HP19 8ET
11A,NHS WEST HAMPSHIRE CCG,HAMPSHIRE,SO50 5PB
11C,"NHS WINDSOR, ASCOT AND MAIDENHEAD CCG",BERKSHIRE,SL4 3DP
11D,NHS WOKINGHAM CCG,BERKSHIRE,RG6 5HZ
11E,NHS BATH AND NORTH EAST SOMERSET CCG,AVON,BA2 5RP
11H,NHS BRISTOL CCG,AVON,BS1 3NX
11J,NHS DORSET CCG,DORSET,DT1 1TG
11M,NHS GLOUCESTERSHIRE CCG,GLOUCESTERSHIRE,GL3 4FE
11N,NHS KERNOW CCG,CORNWALL,PL25 5AS
11T,NHS NORTH SOMERSET CCG,AVON,BS21 6FW
11X,NHS SOMERSET CCG,SOMERSET,BA22 8HR
12A,NHS SOUTH GLOUCESTERSHIRE CCG,AVON,BS16 7FL
12D,NHS SWINDON CCG,WILTSHIRE,SN1 1LH
12F,NHS WIRRAL CCG,MERSEYSIDE,CH41 5AL
12G,"CHESHIRE, WARRINGTON AND WIRRAL COMMISSIONING HUB",WEST YORKSHIRE,LS2 7UE
12H,"DURHAM, DARLINGTON AND TEES COMMISSIONING HUB",WEST YORKSHIRE,LS2 7UE
12J,GREATER MANCHESTER COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12K,LANCASHIRE COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12L,MERSEYSIDE COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12M,"CUMBRIA, NORTHUMBERLAND, TYNE AND WEAR COMMISSIONING HUB",WEST YORKSHIRE,LS2 7UE
12N,NORTH YORKSHIRE AND HUMBER COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12P,SOUTH YORKSHIRE AND BASSETLAW COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12Q,WEST YORKSHIRE COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12R,"ARDEN, HEREFORDSHIRE AND WORCESTERSHIRE COMMISSIONING HUB",WEST YORKSHIRE,LS2 7UE
12T,BIRMINGHAM AND THE BLACK COUNTRY COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12V,DERBYSHIRE AND NOTTINGHAMSHIRE COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12W,EAST ANGLIA COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12X,ESSEX COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
12Y,HERTFORDSHIRE AND THE SOUTH MIDLANDS COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13A,LEICESTERSHIRE AND LINCOLNSHIRE COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13C,SHROPSHIRE AND STAFFORDSHIRE COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13G,"BATH, GLOUCESTERSHIRE, SWINDON AND WILTSHIRE COMMISSIONING HUB",WEST YORKSHIRE,LS2 7UE
13H,"BRISTOL, NORTH SOMERSET, SOMERSET AND SOUTH GLOUCESTERSHIRE COMMISSIONING HUB",WEST YORKSHIRE,LS2 7UE
13J,"DEVON, CORNWALL AND ISLES OF SCILLY COMMISSIONING HUB",WEST YORKSHIRE,LS2 7UE
13K,KENT AND MEDWAY COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13L,SURREY AND SUSSEX COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13M,THAMES VALLEY COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13N,WESSEX COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13P,NHS BIRMINGHAM CROSSCITY CCG,WEST MIDLANDS,B16 9PA
13Q,NATIONAL COMMISSIONING HUB 1,WEST YORKSHIRE,LS2 7UE
13R,LONDON COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13T,NHS NEWCASTLE GATESHEAD CCG,TYNE AND WEAR,NE15 8NY
13V,YORKSHIRE AND HUMBER COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13W,LANCASHIRE AND GREATER MANCHESTER COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13X,CUMBRIA AND NORTH EAST COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
13Y,CHESHIRE AND MERSEYSIDE COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
14A,NORTH MIDLANDS COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
14C,WEST MIDLANDS COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
14D,CENTRAL MIDLANDS COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
14E,EAST COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
14F,SOUTH WEST COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
14G,SOUTH EAST COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
14H,SOUTH CENTRAL COMMISSIONING HUB,WEST YORKSHIRE,LS2 7UE
99A,NHS LIVERPOOL CCG,MERSEYSIDE,L1 4AZ
99C,NHS NORTH TYNESIDE CCG,TYNE AND WEAR,NE29 7ST
99D,NHS SOUTH LINCOLNSHIRE CCG,LINCOLNSHIRE,LN4 2HN
99E,NHS BASILDON AND BRENTWOOD CCG,ESSEX,SS14 3HG
99F,NHS CASTLE POINT AND ROCHFORD CCG,ESSEX,SS14 3HG
99G,NHS SOUTHEND CCG,ESSEX,SS2 6HZ
99H,NHS SURREY DOWNS CCG,SURREY,KT22 7TW
99J,NHS WEST KENT CCG,KENT,TN9 1RE
99K,NHS HIGH WEALD LEWES HAVENS CCG,EAST SUSSEX,BN7 2PB
99M,NHS NORTH EAST HAMPSHIRE AND FARNHAM CCG,HAMPSHIRE,GU11 1AY
99N,NHS WILTSHIRE CCG,WILTSHIRE,SN10 5EQ
99P,"NHS NORTHERN, EASTERN AND WESTERN DEVON CCG",DEVON,EX2 7JU
99Q,NHS SOUTH DEVON AND TORBAY CCG,DEVON,TQ2 7FF
''')

ccg_=dict()
reader=csv.reader(buf)
for i in reader:
  ccg_[i[0]]=i


def name(x):
  if x in ccg_:
    return ccg_[x][1]
  else:
    return x

def county(x):
  return ccg_[x][2]

def ccgs():
  return set(ccg_)
